[package]
name = "tssh"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6"
inquire = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
once_cell = "1.19"